### ISSUE TITLE
Import to DevStudio - unused imports warning

### ISSUE THREAD

**Issue by tsedmik** [jboss-fuse/fuse-apicurito-generator#11]
It looks like, there are not needed imports in _Application.java_ class in the generated project.
![unused-imports](https://user-images.githubusercontent.com/5408450/47140773-6337fc00-d2bf-11e8-9172-725b381684a9.png)

**Comment by apupier** [comment]
@tsedmik PR merged with a fix. I think there is no dashboard for this project. I let you close the PR when it has been validated by QE? or I close directly?

**Comment by tsedmik** [comment]
@apupier great - I have a green build on CI - https://jbdsis-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Apicurito/job/fuse-apicurito-generator-import-project/. Thank you for the fix ;-)
