### ISSUE TITLE
jb-amq-7-brew repository seems useless or 

### ISSUE THREAD

**Issue by apupier** [jboss-fuse/fuse-apicurito-generator#17]
or the comment "for Artemis" is not accurate as I found no Artemis dependency

https://github.com/jboss-fuse/fuse-apicurito-generator/blob/4f1a5ab81beb17eb50b3f9dbb4ee4ba7a8aff784/pom.xml#L83-L92

**Comment by bfitzpat** [comment]
@chirino So far as we can tell, we don't need the Artemis/jb-amq-7-brew repository to build the Apicurito fuse generator. Did that get in as a copy/paste artifact somehow?

**Comment by bfitzpat** [comment]
Created PR to remove unneeded repo - https://github.com/jboss-fuse/fuse-apicurito-generator/pull/23

**Comment by bfitzpat** [comment]
Merged https://github.com/jboss-fuse/fuse-apicurito-generator/commit/42464d027a490e79902b8a2e4bfbc746a1ef95cc

@tsedmik can you verify?

**Comment by tsedmik** [comment]
@bfitzpat verified with master branch
