### ISSUE TITLE
Generated camel file from petstore is xml invalid 

### ISSUE THREAD

**Issue by apupier** [jboss-fuse/fuse-apicurito-generator#30]
using https://github.com/jboss-fuse/fuse-apicurito-generator/blob/master/src/test/resources/petstore-swagger.json

it generates an invalid camel file:

![image](https://user-images.githubusercontent.com/1105127/49654040-06db9800-fa37-11e8-9796-2892df731e06.png)

**Comment by zregvart** [comment]
Should be fixed via #28
