### ISSUE TITLE
Import to DevStudio + Fuse Tooling - missing IDs

### ISSUE THREAD

**Issue by tsedmik** [jboss-fuse/fuse-apicurito-generator#9]
Generated projects lack id attributes in their Camel routes. Fuse Tooling requires unique id values of all Camel elements. Therefore, a lot of warnings appear, once you import a generated project into Fuse Tooling.
![screenshot from 2018-10-04 15-57-55](https://user-images.githubusercontent.com/5408450/46479321-164c2400-c7ef-11e8-94da-dbc858eadae9.png)

Could the generator create Camel routes with id attributes defined?

**Comment by chirino** [comment]
This seems like a problem in Fuse Tooling.  Why is it generating warnings.  If it needs ids, it should add those id's itself.

**Comment by chirino** [comment]
But it seems it's easier to fix the generator than fixing this in the IDE.

**Comment by bfitzpat** [comment]
I'll look into this. The tooling should update the config to add the ids, but it may not in the parameter case.

**Comment by bfitzpat** [comment]
@tsedmik can you attach a zip with your generated project?

**Comment by apupier** [comment]
the tooling is adding the id only when opening the Camel editor.

**Comment by tsedmik** [comment]
@bfitzpat here is an example of generated project from the generator without ids --> [example2.zip](https://github.com/jboss-fuse/fuse-apicurito-generator/files/2448029/example2.zip)

**Comment by bfitzpat** [comment]
Created a PR here - https://github.com/jboss-fuse/fuse-apicurito-generator/pull/10 - this should do the trick to add IDs to the template directly where we can and then auto-generate IDs for the Rest DSL elements we are bringing in from the Apicurio-generated Rest DSL

**Comment by bfitzpat** [comment]
PR merged
